#!/usr/bin/env node
const command = process.argv[2].trim();
if(command == '') return;

const compiler = require('child_process').spawn('./psc', [], {stdio: 'pipe'});
compiler.stdin.write(command);
compiler.stdin.end();

let code = "";
compiler.stdout.on('data', data => code += data.toString());
compiler.stdout.on('end', () => {
	(new (require('vm').Script)(code)).runInThisContext()
});