#!/usr/bin/env node
const command = process.argv.slice(2).join(' ').trim();
if(command == '') return;
require('child_process').exec(`echo ${command} | ./psc`, (error, stdout, stderr) => {
	if(error) throw error;
	(new (require('vm').Script)(stdout)).runInThisContext()
});